# Generated by Django 5.2.4 on 2025-07-20 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cars',
            options={},
        ),
    ]
